#!/usr/bin/bash

docker-compose -f docker-compose.client.yml up -d

#docker run -d --rm \
#    --net=tickdocker_influxnet \
#    -v $PWD/../etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro \
#    telegraf:1.4.0
