version: '3'

networks:
  influxnet:
    driver: bridge

# current: ./data
#volumes:
#  tick_data:

services:

  influxdb:
    image: influxdb:1.4.3-alpine
    restart: always
    volumes:
      - ./data/influxdb:/var/lib/influxdb
      - ./certs:/etc/ssl/influxdb
      - ./etc/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    networks:
      influxnet:
    ports:
      - "8086:8086"

  chronograf:
    image: chronograf:1.4.1-alpine
    restart: always
    environment:
      INFLUXDB_URL: https://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    command: chronograf --host 0.0.0.0 --port 8888 --basepath /chronograf --prefix-routes --influxdb-url=https://influxdb:8086 --kapacitor-url=http://kapacitor:9092
    depends_on:
      - influxdb
      - kapacitor
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    networks:
      influxnet:
    ports:
      - "8888:8888"

  kapacitor:
    image: kapacitor:1.4.0-alpine
    restart: always
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_LOAD_DIR: /etc/kapacitor/load
    depends_on:
      - influxdb
    networks:
      influxnet:
    ports:
      - "9092:9092"
    volumes:
      - ./certs:/etc/ssl/influxdb
      - ./etc/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf
      - ./etc/kapacitor/load:/etc/kapacitor/load
    command: kapacitord -config /etc/kapacitor/kapacitor.conf
