version: '3'

networks:
  influxnet:
    driver: bridge

volumes:
  influx_data:

services:

  influxdb:
    image: influxdb:1.3.5
    volumes:
      - influx_data:/var/lib/influxdb
      - ./certs:/etc/ssl/influxdb
      - ./etc/influxdb.conf:/etc/influxdb/influxdb.conf
    networks:
      influxnet:
    ports:
      - "8086:8086"

  chronograf:
    image: chronograf:1.3.8
    environment:
      INFLUXDB_URL: https://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    depends_on:
      - influxdb
      - kapacitor
    networks:
      influxnet:
    ports:
      - "8888:8888"

  kapacitor:
    image: kapacitor:1.3.3
    environment:
      KAPACITOR_HOSTNAME: kapacitor
    depends_on:
      - influxdb
    networks:
      influxnet:
    ports:
      - "9092:9092"
    volumes:
      - ./certs:/etc/ssl/influxdb
      - ./etc/kapacitor.conf:/etc/kapacitor/kapacitor.conf
    command: kapacitord -config /etc/kapacitor/kapacitor.conf
