version: '3'

networks:
  tickdocker_influxnet:
    external: true

services:
  nginx:
    #image: nginx:1.13.8-alpine
    image: nginx:1.12
    volumes:
      - ./etc/nginx/:/etc/nginx/
      - ./certs/nginx:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - tickdocker_influxnet
