version: '3'

networks:
  influxnet:
    driver: bridge

# testing: ./data
volumes:
  tick_data:
#    external: true

services:

  influxdb:
    image: influxdb:1.4.3
    restart: unless-stopped
    volumes:
      #- ./data/influxdb:/var/lib/influxdb
      - tick_data:/var/lib/influxdb
      - ./certs/influxdb:/etc/ssl/influxdb
      - ./etc/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    networks:
      influxnet:
    ports:
      - "8086:8086"

  chronograf:
    image: chronograf:1.3.10
    restart: unless-stopped
    environment:
      INFLUXDB_URL: https://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    depends_on:
      - influxdb
      - kapacitor
    volumes:
      #- ./data/chronograf:/var/lib/chronograf
      - tick_data:/var/lib/chronograf
    networks:
      influxnet:
    # --- WITH proxy: start
    command: chronograf --host 0.0.0.0 --port 8888 --basepath /chronograf --prefix-routes --influxdb-url=https://influxdb:8086 --kapacitor-url=http://kapacitor:9092
    expose:
      - "8888"
    # --- WITH proxy: end --log-level=debug
    # --- WITHOUT proxy: start
    #command: chronograf  --host 0.0.0.0 --port 8888 --influxdb-url=https://influxdb:8086 --kapacitor-url=http://kapacitor:9092
    #ports:
    #  - "8888:8888"
    # --- WITHOUT proxy: end --log-level=debug

  kapacitor:
    image: kapacitor:1.4.0
    restart: unless-stopped
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_LOAD_DIR: /etc/kapacitor/load
    depends_on:
      - influxdb
    networks:
      influxnet:
    expose:
      - "9092"
    volumes:
      - ./certs/influxdb:/etc/ssl/influxdb
      - ./etc/kapacitor/kapacitor.conf:/etc/kapacitor/kapacitor.conf
      - ./etc/kapacitor/load:/etc/kapacitor/load
    command: kapacitord -config /etc/kapacitor/kapacitor.conf
