version: '3'

networks:
  influxnet:
    driver: bridge

services:

  influxdb:
    image: influxdb:1.3.5
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    networks:
      influxnet:
    ports:
      - "8086:8086"

  chronograf:
    image: chronograf:1.3.8
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    networks:
      influxnet:
    depends_on:
      - influxdb
      - kapacitor
    ports:
      - "8888:8888"

  kapacitor:
    image: kapacitor:1.3.3
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    depends_on:
      - influxdb
    networks:
      influxnet:
    ports:
      - "9092:9092"
